language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-26.1-travis-linux-xenial
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial
script:
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - cask install
  - make test
